import pyautogui as pg
import time
time.sleep(4)
#play at https://www.onlinepianist.com/virtual-piano 

pg.press('w', presses = 2)
time.sleep(0.2)
pg.press('e', presses = 1)
time.sleep(0.2)
pg.press('w', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
time.sleep(0.2)
pg.press('z', presses = 1)
time.sleep(0.2)
pg.press('w', presses = 2)
time.sleep(0.2)
pg.press('e', presses = 1)
time.sleep(0.2)
pg.press('w', presses = 1)
time.sleep(0.2)
pg.press('c', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
time.sleep(0.2)
pg.press('w', presses = 2)
time.sleep(0.2)
pg.press('n', presses = 1)
time.sleep(0.2)
pg.press('v', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
time.sleep(0.2)
pg.press('z', presses = 1)
time.sleep(0.2)
pg.press('e', presses = 1)
time.sleep(0.2)
pg.press('b', presses = 2)
time.sleep(0.2)
pg.press('v', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
time.sleep(0.2)
pg.press('c', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
pg.press('w', presses = 2)
time.sleep(0.2)
pg.press('e', presses = 1)
time.sleep(0.2)
pg.press('w', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
time.sleep(0.2)
pg.press('z', presses = 1)
time.sleep(0.2)
pg.press('w', presses = 2)
time.sleep(0.2)
pg.press('e', presses = 1)
time.sleep(0.2)
pg.press('w', presses = 1)
time.sleep(0.2)
pg.press('c', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
time.sleep(0.2)
pg.press('w', presses = 2)
time.sleep(0.2)
pg.press('n', presses = 1)
time.sleep(0.2)
pg.press('v', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
time.sleep(0.2)
pg.press('z', presses = 1)
time.sleep(0.2)
pg.press('e', presses = 1)
time.sleep(0.2)
pg.press('b', presses = 2)
time.sleep(0.2)
pg.press('v', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
time.sleep(0.2)
pg.press('c', presses = 1)
time.sleep(0.2)
pg.press('t', presses = 1)
